$(document).ready(function(){
$(".clickable").click(function(){
  $("#javascript").toggle();
  $("#modulo").toggle();
  $("#return").toggle();
  $("#operators").toggle();
  $("#plusEqual").toggle();
  $("#nan").toggle();
  $("#function").toggle();
  $("#method").toggle();
  $("#argument").toggle();
  $("#string").toggle();
  $("#chaining").toggle();
  $("#escape").toggle();
  $("#alert").toggle();
  $("#comment").toggle();
  $("#boolean").toggle();
  $("#undefined").toggle();
  $("#parameter").toggle();
  $("#variable").toggle();
});
});
